### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by warbe-maker** [navikt/.github#2]
I followed the (only) instruction I understood:
Copy two lines to my _config.yml (the only yml file I have with my Minima Jekyll Blog. As a result I got a Jekyll error "unable to build ...". I removed the two lines again.
I am very sorry but my knowledge is apparently too limited for using access tokens.
I use my blog as a cloned repo and do not have a local (windows) installation.

**Comment by Kyrremann** [comment]
Hi, I'm pretty sure you posted your issue to the wrong repository/organization. This repo specifically is a dead-ish repo for configuration of other navikt-repo.
